# Building & testing the orchestration backend

name: Orchestration pipeline (java)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  LANG: "fr_FR.UTF-8"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
