# Building & testing the orchestration backend

name: Orchestration pipeline (java)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  LANG: "fr_FR.UTF-8"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macOS-latest]
    defaults:
      run:
        working-directory: ./back-fitzhi
    steps:
    - uses: actions/checkout@v2
    - name: "Setup locale settings on the Ubuntu instance for fr_FR.UTF8"
      run: |
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8
      if: (matrix.os == 'ubuntu-latest')
    - name: "Testing locale settings"
      run: sudo locale
    - name: "Simple Test for macOS"
      run: sudo locale -a
      if: (matrix.os == 'macOS-latest')
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Display Maven settings
      run: mvn --version
    - name: Build with Maven
      run: |
        mvn --batch-mode clean package -DskipTests
      if: (matrix.os == 'ubuntu-latest')
   - name: Test with maven
      run: mvn --batch-mode test
