# Building & testing the orchestration backend

name: Orchestration pipeline (java)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  LANG: "fr_FR.UTF-8"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: "Setup locale settings on the Ubuntu instance for fr_FR.UTF8"
      run: |
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8
#      if: (matrix.os == 'ubuntu-latest')
#    - name: "Testing locale settings"
#        run: sudo locale
#      if: (matrix.os == 'ubuntu-latest') || (matrix.os == 'macOS-latest')
